# ── Prefix Key ──────────────────────────
unbind C-b
set -g prefix C-t
bind C-t send-prefix

# ── General Settings ────────────────────
set -g escape-time 0
set -g history-limit 10000
set -g default-command "fish"
set -g focus-events on

# ── Terminal Colors ─────────────────────
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# ── Styles ──────────────────────────────
set -g status-left "[#{?client_prefix,##,#S}] "
set -g status-right "%a %b %-d %R"
set -g status-style bg="#1c1c1c",fg=default

set -g window-status-format "#I:#{b:pane_current_path}"
set -g window-status-style bg=default,fg=default
set -g window-status-current-format "#I:#{b:pane_current_path}"
set -g window-status-current-style bg=default,fg=yellow

set -g pane-border-style bg=default,fg="#1c1c1c"
set -g pane-active-border-style bg=default,fg="#1c1c1c"

set -g message-style bg="#1c1c1c",fg=yellow
set -g mode-style bg="#424242",fg=default

# ── Key Bindings ────────────────────────
bind c new-window -c "#{pane_current_path}"
bind h split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"
bind r source-file ~/.tmux.conf \; display "Config reloaded!"
bind ] run-shell "pbpaste | tmux load-buffer - && tmux paste-buffer"

bind C-n next-window
bind C-p previous-window
bind C-o select-pane -t :.+
bind C-] run-shell "pbpaste | tmux load-buffer - && tmux paste-buffer"
bind Escape copy-mode

bind -T copy-mode C-w send -X copy-pipe-and-cancel "pbcopy"
