(deftheme my "My theme.")

(let ((red "red")
      (green "green")
      (yellow "yellow")
      (blue "blue")
      (magenta "magenta")
      (cyan "cyan")
      (orange "color-173")
      (comment "color-246")
      (region "color-238")
      (mode-line "color-235"))
  (custom-theme-set-faces
   'my
   `(custom-variable-tag ((t (:foreground ,blue))))
   `(eldoc-highlight-function-argument ((t (:foreground ,orange))))
   `(error ((t (:foreground ,red))))
   `(escape-glyph ((t (:foreground ,magenta))))
   `(font-lock-builtin-face ((t (:foreground ,cyan))))
   `(font-lock-comment-delimiter-face ((t (:foreground ,comment))))
   `(font-lock-comment-face ((t (:foreground ,comment))))
   `(font-lock-constant-face ((t (:foreground ,cyan))))
   `(font-lock-doc-face ((t (:foreground ,comment))))
   `(font-lock-function-name-face ((t (:foreground ,blue))))
   `(font-lock-keyword-face ((t (:foreground ,magenta))))
   `(font-lock-negation-char-face ((t (:foreground ,green))))
   `(font-lock-preprocessor-face ((t (:foreground ,magenta))))
   `(font-lock-regexp-grouping-backslash ((t (:foreground ,yellow))))
   `(font-lock-regexp-grouping-construct ((t (:foreground ,magenta))))
   `(font-lock-string-face ((t (:foreground ,green))))
   `(font-lock-type-face ((t (:foreground ,yellow))))
   `(font-lock-variable-name-face ((t (:foreground ,orange))))
   `(font-lock-warning-face ((t (:foreground ,red))))
   `(fringe ((t (:background ,mode-line))))
   `(header-line ((t (:foreground ,magenta :background ,mode-line))))
   `(hl-line ((t (:background ,mode-line))))
   `(ido-first-match ((t (:foreground ,orange))))
   `(ido-only-match ((t (:foreground ,red))))
   `(ido-subdir ((t (:foreground ,blue))))
   `(isearch ((t (:foreground ,orange :inverse-video t))))
   `(isearch-fail ((t (:foreground ,red))))
   `(lazy-highlight ((t (:foreground ,yellow :inverse-video t))))
   `(link ((t (:foreground ,blue))))
   `(link-visited ((t (:foreground ,magenta))))
   `(linum ((t (:background ,mode-line))))
   `(minibuffer-prompt ((t (:foreground ,blue))))
   `(mode-line ((t (:background ,mode-line))))
   `(mode-line-buffer-id ((t (:foreground ,magenta))))
   `(mode-line-inactive ((t (:background ,mode-line))))
   `(region ((t (:background ,region))))
   `(secondary-selection ((t (:background ,mode-line))))
   `(shadow ((t (:foreground ,comment))))
   `(success ((t (:foreground ,green))))
   `(warning ((t (:foreground ,orange))))
   `(widget-button ((t (:underline t))))
   `(widget-field ((t (:background ,mode-line))))))

(provide-theme 'my)
