(deftheme my "My theme.")

(let ((red "red")
      (green "green")
      (yellow "yellow")
      (blue "blue")
      (magenta "magenta")
      (cyan "cyan")
      (orange "color-173")
      (comment "color-246")
      (region "color-238")
      (mode-line "color-235"))

  (custom-theme-set-faces-simply
   'my
   `(custom-variable-tag :foreground ,blue)
   `(eldoc-highlight-function-argument :foreground ,orange)
   `(error :foreground ,red)
   `(escape-glyph :foreground ,magenta)
   `(font-lock-builtin-face :foreground ,cyan)
   `(font-lock-comment-delimiter-face :foreground ,comment)
   `(font-lock-comment-face :foreground ,comment)
   `(font-lock-constant-face :foreground ,cyan)
   `(font-lock-doc-face :foreground ,comment)
   `(font-lock-function-name-face :foreground ,blue)
   `(font-lock-keyword-face :foreground ,magenta)
   `(font-lock-negation-char-face :foreground ,green)
   `(font-lock-preprocessor-face :foreground ,magenta)
   `(font-lock-regexp-grouping-backslash :foreground ,yellow)
   `(font-lock-regexp-grouping-construct :foreground ,magenta)
   `(font-lock-string-face :foreground ,green)
   `(font-lock-type-face :foreground ,yellow)
   `(font-lock-variable-name-face :foreground ,orange)
   `(font-lock-warning-face :foreground ,red)
   `(fringe :background ,mode-line)
   `(header-line :foreground ,magenta :background ,mode-line)
   `(hl-line :background ,mode-line)
   `(ido-first-match :foreground ,orange)
   `(ido-only-match :foreground ,red)
   `(ido-subdir :foreground ,blue)
   `(isearch :foreground ,orange :inverse-video t)
   `(isearch-fail :foreground ,red)
   `(lazy-highlight :foreground ,yellow :inverse-video t)
   `(link :foreground ,blue)
   `(link-visited :foreground ,magenta)
   `(linum :background ,mode-line)
   `(match :foreground ,yellow :inverse-video t)
   `(minibuffer-prompt :foreground ,blue)
   `(mode-line :background ,mode-line)
   `(mode-line-buffer-id :foreground ,magenta)
   `(mode-line-inactive :background ,mode-line)
   `(region :background ,region)
   `(secondary-selection :background ,mode-line)
   `(shadow :foreground ,comment)
   `(success :foreground ,green)
   `(warning :foreground ,orange)
   `(widget-button :underline t)
   `(widget-field :background ,mode-line)))

(provide-theme 'my)
